stun-turn-server:
    image: buanet/coturn:latest
    container_name: stun-turn-server
    restart: always
    network_mode: host
    environment:
      - LISTENING_IP_ADDRESS=0.0.0.0
      - EXTERNAL_IP_ADDDRESS=xxx.xxx.xxx.xxx
      - TURN_PORT=3478
      - TURN_USERNAME=<user>
      - TURN_PASSWORD=<passwort>